global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows;
global using System.Windows.Threading;

global using Atc.DependencyInjection;
global using Atc.Hosting;
global using Atc.SourceGenerators.Annotations;
global using Atc.Wpf.Notifications;
global using Atc.XamlToolkit.Controls.Attributes;
global using Atc.XamlToolkit.Messaging;
global using Atc.XamlToolkit.Mvvm;

global using AtcSoft.CameraWall.Wpf.Services.Internal;
global using AtcSoft.VideoEngine;
global using AtcSoft.VideoSurveillance.Enums;
global using AtcSoft.VideoSurveillance.Models.Settings;
global using AtcSoft.VideoSurveillance.Wpf.Core;
global using AtcSoft.VideoSurveillance.Wpf.Core.Events;
global using AtcSoft.VideoSurveillance.Wpf.Core.Factories;
global using AtcSoft.VideoSurveillance.Wpf.Core.Messages;
global using AtcSoft.VideoSurveillance.Wpf.Core.Models;
global using AtcSoft.VideoSurveillance.Wpf.Core.Resources;
global using AtcSoft.VideoSurveillance.Wpf.Core.Services;
global using AtcSoft.VideoSurveillance.Wpf.Core.UserControls;
global using Microsoft.Extensions.Logging;

global using ApplicationHelper = AtcSoft.VideoSurveillance.Helpers.ApplicationHelper;
global using BoundingBox = AtcSoft.VideoSurveillance.Models.BoundingBox;
global using CameraLayoutItem = AtcSoft.VideoSurveillance.Models.CameraLayoutItem;
global using ConnectionState = Atc.Network.ConnectionState;
global using IGitHubReleaseService = AtcSoft.VideoSurveillance.Services.IGitHubReleaseService;
global using IMediaCleanupService = AtcSoft.VideoSurveillance.Services.IMediaCleanupService;
global using IMediaPipeline = AtcSoft.VideoSurveillance.Services.IMediaPipeline;
global using IMotionDetectionService = AtcSoft.VideoSurveillance.Services.IMotionDetectionService;
global using IRecordingSegmentationService = AtcSoft.VideoSurveillance.Services.IRecordingSegmentationService;
global using IThumbnailGeneratorService = AtcSoft.VideoSurveillance.Services.IThumbnailGeneratorService;
global using IUsbCameraWatcher = AtcSoft.VideoSurveillance.Services.IUsbCameraWatcher;
global using MediaCleanupCompletedEventArgs = AtcSoft.VideoSurveillance.Events.MediaCleanupCompletedEventArgs;
global using MediaCleanupDirectoryResult = AtcSoft.VideoSurveillance.Helpers.MediaCleanupDirectoryResult;
global using MediaCleanupResult = AtcSoft.VideoSurveillance.Models.MediaCleanupResult;
global using MediaCleanupRunError = AtcSoft.VideoSurveillance.Helpers.MediaCleanupRunError;
global using MediaCleanupRunner = AtcSoft.VideoSurveillance.Helpers.MediaCleanupRunner;
global using MediaCleanupRunResult = AtcSoft.VideoSurveillance.Helpers.MediaCleanupRunResult;
global using MotionDetectedEventArgs = AtcSoft.VideoSurveillance.Events.MotionDetectedEventArgs;
global using RecordingSegmentedEventArgs = AtcSoft.VideoSurveillance.Events.RecordingSegmentedEventArgs;
global using RecordingSession = AtcSoft.VideoSurveillance.Models.RecordingSession;
global using RecordingSlotCalculator = AtcSoft.VideoSurveillance.Helpers.RecordingSlotCalculator;
global using RecordingStateChangedEventArgs = AtcSoft.VideoSurveillance.Events.RecordingStateChangedEventArgs;
global using SegmentationReason = AtcSoft.VideoSurveillance.Events.SegmentationReason;
global using TimelapseFrameCapturedEventArgs = AtcSoft.VideoSurveillance.Events.TimelapseFrameCapturedEventArgs;
global using UniqueFilename = AtcSoft.VideoSurveillance.Helpers.UniqueFilename;
global using UsbCameraEventArgs = AtcSoft.VideoSurveillance.Events.UsbCameraEventArgs;