global using AtcSoft.VideoSurveillance.Api.Domain.ApiHandlers.Cameras;
global using AtcSoft.VideoSurveillance.Api.Domain.ApiHandlers.Devices;
global using AtcSoft.VideoSurveillance.Api.Domain.ApiHandlers.Layouts;
global using AtcSoft.VideoSurveillance.Api.Domain.ApiHandlers.Recordings;
global using AtcSoft.VideoSurveillance.Api.Domain.ApiHandlers.Settings;
global using AtcSoft.VideoSurveillance.Api.Domain.Mapping;
global using AtcSoft.VideoSurveillance.Enums;
global using AtcSoft.VideoSurveillance.Models;
global using AtcSoft.VideoSurveillance.Models.Settings;
global using AtcSoft.VideoSurveillance.Services;
global using Microsoft.AspNetCore.Http.HttpResults;
global using VideoSurveillance.Generated.Cameras.Models;
global using VideoSurveillance.Generated.Cameras.Parameters;
global using VideoSurveillance.Generated.Layouts.Models;
global using VideoSurveillance.Generated.Layouts.Parameters;
global using VideoSurveillance.Generated.Recordings.Models;
global using VideoSurveillance.Generated.Recordings.Parameters;
global using VideoSurveillance.Generated.Settings.Models;
global using VideoSurveillance.Generated.Settings.Parameters;
global using ApiCameraProtocol = VideoSurveillance.Generated.Cameras.Models.CameraProtocol;
global using ApiCameraSource = VideoSurveillance.Generated.Cameras.Models.CameraSource;
global using CoreCameraProtocol = AtcSoft.VideoSurveillance.Enums.CameraProtocol;
global using CoreCameraSource = AtcSoft.VideoSurveillance.Enums.CameraSource;