<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <TestingPlatformCommandLineArguments>--ignore-exit-code 8</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\AtcSoft.VideoEngine\AtcSoft.VideoEngine.csproj" />
  </ItemGroup>

</Project>